filebeat.inputs:
- type: log
  enabled: true
  paths:
  - /usr/share/filebeat/logs/laravel/*.log
  multiline.pattern: '^\[\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}\]'
  multiline.negate: true
  multiline.match: after
  processors:
  - add_fields:
      target: fields
      fields:
        logs_type: 'laravel_log' 
- type: log
  enabled: true
  paths:
  - /usr/share/filebeat/logs/nginx/error.log
  fields:
  document_type: nginx_error
  processors:
  - add_fields:
      target: fields
      fields:
        logs_type: 'nginx_error_log'
- type: log
  enabled: true
  paths:
  - /usr/share/filebeat/logs/nginx/access.log
  fields:
  document_type: nginx_access
  processors:
  - add_fields:
      target: fields
      fields:
        logs_type: 'nginx_access_log'
output.logstash:
  hosts: ['192.168.11.250:9600
']
#output.console:
#  pretty: true
